version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: notas_db
      POSTGRES_USER: yuritabacof
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      
