# Generated by Django 4.2.5 on 2023-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_tag_note_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="", max_length=10),
        ),
    ]
